name: Build SCSS

# On pushing to main, build CSS
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Build CSS from SCSS
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup build environment
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Remove dist from git tracking if it exists
      - name: Remove dist from git tracking (if it exists)
        run: |
          if [ -d "dist" ]; then
            git rm -r --cached dist
            echo "dist/" >> .gitignore
            git add .gitignore
            git commit -m "Remove dist directory from version control"
          fi

      # Build the CSS
      - name: Compile SCSS
        run: npm run build

      # Commit generated and minified CSS back to repo
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist/*
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-build: compiled SCSS to CSS"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
