name: Build SCSS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Compile SCSS
      - name: Compile SCSS
        run: npm run build

      - name: Commit changes (if any)
        run: |
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Your commit message"
            git push origin main
          else
            echo "No changes to commit."
          fi
